### ISSUE TITLE
Object with two names, what would be best to do?

### ISSUE THREAD

**Issue by andrescarmona** [njcuk9999/apero-drs#655] opened 2020-11-16 12:13 UTC
We have a kind of small issue with an object it has two names “HD189733” and “HD 189733b”
so the DRS thinks they are two different guys.

Ideally we would like to use the whole data set for constructing the templates for telluric correction.
The question were to change the DRSOBJN keyword

1. in the pp files?
2. in the e2dsff files?

Another option is to extract independently HD 189733b  and use the copy the already existing HD189733 template 
to a HD189733B template and do the telluric correction
using
RUN_FTELLU1 = True
RUN_FTELLU2 = False
RUN_FTELLU3 = False

ideas?

Cheers!

Andres

**Comment by njcuk9999** [comment] 2020-11-16 14:05
I think this will hopefully be fixed with these "aliases" we have, in the future - please make a note of it to add it to the aliases column in the google sheet when it is finalized.

Best thing you can do for now is update the raw files from CFHT to correct the OBJECT key - they will then go through the DRS, or as you say edit the pp files (but then you have to remember to do this if you re-preprocess in the future.

**Comment by njcuk9999** [comment] 2020-11-16 14:06
Actually I'm also going to tag @vandalt as he is dealing with the google sheet of object names.

**Comment by vandalt** [comment] 2020-12-07 13:45
The scripts I use to manage the Google sheet should automatically  flag cases like this in the future. It did for this specific one, so "HD 189433b" has been added in the alias column. I'll let @njcuk9999 close the issue, because maybe he wants to keep it open until this has been fully included in the DRS.

**Comment by njcuk9999** [comment] 2020-12-07 16:15
Yep I'll leave this open until I've confirmed a few things internally:
1. when do we update the database with this google sheet
2. what order do we try to get the object details
3. tests that this actually works on good/bad object names

**Closed** 2021-04-01 16:09 UTC
